CREATE TABLE adults (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(255),
    phone VARCHAR(20) NOT NULL,
    zip_code VARCHAR(9) NOT NULL,
    street VARCHAR(255) NOT NULL,
    house_number VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    neighborhood VARCHAR(100),
    civil_status ENUM('SINGLE','MARRIED','WIDOWED','DIVORCED') NOT NULL,
    spouse_id BIGINT,
    role ENUM('STUDENT', 'MEMBER', 'VOLUNTEER', 'LEADER', 'PASTOR') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_image_authorized BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    church_name VARCHAR(255),
    leader_name VARCHAR(255),
    baptism_date DATE,
    CONSTRAINT fk_adult_spouse FOREIGN KEY (spouse_id) REFERENCES adults(id)
);

